from atlas.services.areas import archive_area, create_area, get_area, list_areas, update_area
from atlas.services.entries import amend_entry, delete_entry, log_entry
from atlas.services.errors import AlreadyExistsError, NotFoundError, ServiceError, ValidationError
from atlas.services.goals import (
    GoalBoardColumn,
    GoalBoardTask,
    GoalBoardWeek,
    GoalDetail,
    GoalProgressReport,
    GoalsBoard,
    MilestoneInput,
    create_goal,
    get_goal,
    get_goal_detail,
    goal_progress,
    goals_board,
    list_goals,
    toggle_milestone,
    update_goal,
)
from atlas.services.habits import (
    HabitStatus,
    create_habit,
    get_habit,
    habit_status,
    list_habits,
    update_habit,
)
from atlas.services.home import HomeWeek, home_week
from atlas.services.journal import JournalDay, journal_day, log_journal
from atlas.services.metrics import (
    archive_metric,
    create_metric,
    get_metric,
    list_metrics,
    update_metric,
)
from atlas.services.port import export_all, import_all
from atlas.services.screen import (
    ScreenBudgetStatus,
    ScreenView,
    create_screen_app,
    create_screen_budget,
    create_screen_category,
    get_screen_app,
    get_screen_budget,
    get_screen_category,
    list_screen_apps,
    list_screen_budgets,
    list_screen_categories,
    screen_view,
    update_screen_app,
    update_screen_budget,
    update_screen_category,
)
from atlas.services.seed import SeedSummary, demo_payload, seed_demo
from atlas.services.slips import SlipsWeek, log_slip, slips_week
from atlas.services.tasks import create_task, list_tasks, tasks_done_in_week, update_task
from atlas.services.updates import UpdatesStatus, log_update, updates_status
from atlas.services.views import (
    AreaView,
    LoggedEntry,
    MetricSnapshot,
    TodayView,
    WeekDayCell,
    WeekHabit,
    WeekView,
    area_view,
    today_view,
    week_view,
)

__all__ = [
    "AlreadyExistsError",
    "AreaView",
    "GoalBoardColumn",
    "GoalBoardTask",
    "GoalBoardWeek",
    "GoalDetail",
    "GoalProgressReport",
    "GoalsBoard",
    "HabitStatus",
    "HomeWeek",
    "JournalDay",
    "LoggedEntry",
    "MetricSnapshot",
    "MilestoneInput",
    "NotFoundError",
    "SeedSummary",
    "ScreenBudgetStatus",
    "ScreenView",
    "ServiceError",
    "SlipsWeek",
    "TodayView",
    "UpdatesStatus",
    "ValidationError",
    "WeekDayCell",
    "WeekHabit",
    "WeekView",
    "amend_entry",
    "archive_area",
    "archive_metric",
    "area_view",
    "create_area",
    "create_goal",
    "create_habit",
    "create_metric",
    "create_screen_app",
    "create_screen_budget",
    "create_screen_category",
    "create_task",
    "delete_entry",
    "demo_payload",
    "export_all",
    "get_area",
    "get_goal",
    "get_goal_detail",
    "get_habit",
    "get_metric",
    "get_screen_app",
    "get_screen_budget",
    "get_screen_category",
    "goal_progress",
    "goals_board",
    "habit_status",
    "home_week",
    "import_all",
    "journal_day",
    "list_areas",
    "list_goals",
    "list_habits",
    "list_metrics",
    "list_screen_apps",
    "list_screen_budgets",
    "list_screen_categories",
    "list_tasks",
    "log_entry",
    "log_journal",
    "log_slip",
    "log_update",
    "screen_view",
    "seed_demo",
    "slips_week",
    "tasks_done_in_week",
    "today_view",
    "toggle_milestone",
    "update_area",
    "update_goal",
    "update_habit",
    "update_metric",
    "update_screen_app",
    "update_screen_budget",
    "update_screen_category",
    "update_task",
    "updates_status",
    "week_view",
]
